services:
  filehub-server:
    image: exiahuang/filehub-server:latest
    container_name: filehub-server
    ports:
      - "6543:6543"
    volumes:
      - ${DATA_PATH:-.}:/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

